### PR TITLE
Adding Esperanto to supported languages

### PR DESCRIPTION
**Pull request by LaPingvino**
@batisteo, can you check that this works?

### CODE REVIEW

**Comment by LaPingvino** [comment]
This fixes #6

**Comment by darksmo** [comment]
So with Esperanto in theory we have a problem of consistency, as all the other languages have the main country in which the language is spoken. To check this you could:

`cd <project-toplevel-dir>`
`python -m SimpleHTTPServer`
`browse to http://localhost:8000/demo/supportedLanguages.html`

Then see that for any other language we would have something like:

`<flag-image> fi_FI - Finland (Finnish) Suomi (Suomi)`

and then with Esperanto:

`eo - (Esperanto) (Esperanto)`

.

I'm thinking about a solution for this, I mean languages without a country code.

**Comment by LaPingvino** [comment]
I left the fields out completely, I could fill in e.g. World here, and/or XX for the country code, but of course without a country code really is neater (this has been corrected at some point for Linux distros for example), and actually approaching languages from a country point of view is always a minefield.

**Comment by darksmo** [comment]
What I'm saying is that we should solve the general case of countries without languages - not ignoring the issue.

**Comment by darksmo** [comment]
Now should be really fixed - thanks for the pull request though, it's been useful!

**Comment by darksmo** [comment]
I'm going to close this as it should be merged now

**Pull request closed without merging**
